export const SET_TEST = 'SET_TEST';
export const SET_TEST_RESULT = 'SET_TEST_RESULT';
export const SET_TEST_RESULT_TEXT = 'SET_TEST_RESULT_TEXT';
export const UPDATE_RESULTS_COUNT = 'UPDATE_RESULTS_COUNT';
export const SAVE_RESULTS_COUNT = 'SAVE_RESULTS_COUNT';
export const SET_RESULTS_COUNT = 'SET_RESULTS_COUNT';
